services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - .docker/mysql:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orders-app
    restart: always
    ports:
      - "8000:8000"
      - "50051:50051"
      - "8080:8080"
    depends_on:
      - mysql
      - rabbitmq
    env_file:
      - .env
    environment:
      # Override hosts for Docker networking
      DB_HOST: mysql
      DB_PORT: 3306
      RABBITMQ_HOST: rabbitmq
